[package]
authors = ["Francesco Iannelli \"frjnn\"", "Stefano Pacchini \"ste-pac\""]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "neuronika-core"
version = "0.1.0"

[dependencies]
ndarray = "0.15.4"
