[package]
name = "neuronika"
version = "0.1.0"
authors = ["frjnn <f.iannelli.francesco229@gmail.com>", "stepac <stefanopacchini@mail.com>"]
edition = "2021"
description = "Tensors and dynamic neural networks."
keywords = ["deep-learning", "auto-differentiation", "machine-learning", "tensors"]
repository = "https://github.com/neuronika/neuronika"
license = "MPL-2.0"
exclude = ["misc/*"]

[dependencies]
ndarray = {version = "0.15.3", features = ["rayon"]}
rayon = "1.5.1"
ndarray-rand = "0.14.0"
itertools = "0.10.1"
rand = "0.8.4"
rand_distr = "0.4.0"
serde = "1.0.130"
csv = "1.1.6"

[features]
blas = ["ndarray/blas"]
matrixmultiply-threading = ["ndarray/matrixmultiply-threading"]
serialize = ["ndarray/serde"]