[package]
name = "neuronika"
version = "0.1.0"
authors = ["frjnn <f.iannelli.francesco229@gmail.com>", "stepac <stefanopacchini@mail.com>"]
edition = "2018"
description = "Tensors and dynamic neural networks."
keywords = ["deep learning", "automatic differentiation"]

[dependencies]
ndarray = {version = "0.15.3", features = ["rayon"]}
rayon = "1.5.1"
ndarray-rand = "0.14.0"
itertools = "0.10.0"
rand = "0.8.3"
rand_distr = "0.4.0"
serde = "1.0.126"
csv = "1.1.6"

[dev-dependencies]
blas-src = { version = "0.8", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }

[features]
blas = ["ndarray/blas"]
matrixmultiply-threading = ["ndarray/matrixmultiply-threading"]
serialize = ["ndarray/serde"]