[package]
name = "neuronika"
version = "0.1.0"
authors = ["frjnn <f.iannelli.francesco229@gmail.com>", "stepac <stefanopacchini@mail.com>"]
edition = "2018"

[dependencies]
ndarray = {version = "0.15.1", features = ["rayon"]}
ndarray-rand = "0.14.0"
itertools = "0.10.0"
rand = "0.8.3"
rand_distr = "0.4.0"