version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  
jobs:
  build:
    machine: 
      image: ubuntu-2004:202201-02
    steps:
      - checkout

      - run:
          name: Pull xd009642/tarpaulin
          command: docker pull xd009642/tarpaulin

      - run:
          name: Run test and generate coverage report
          command: >-
            docker run --security-opt seccomp=unconfined
            -v $PWD:/volume xd009642/tarpaulin
            cargo tarpaulin --workspace --out Xml --ignore-tests

      - codecov/upload:
          file: cobertura.xml
          
